Repository Tongsuo-Project/Tongsuo, pull requests merged in 2021-11, with the labels that each got.

#109 Support integrity algorithm 128-EIA3
  Configure
  crypto/asn1/standard_methods.h
  crypto/cpt_err.c
  crypto/eia3/build.info
  crypto/eia3/eia3.c
  crypto/eia3/eia3_ameth.c
  crypto/eia3/eia3_local.h
  crypto/eia3/eia3_pmeth.c
  crypto/err/openssl.txt
  crypto/evp/evp_err.c
  crypto/evp/p_lib.c
  crypto/evp/pmeth_lib.c
  doc/man3/EVP_DigestSignInit.pod
  doc/man3/EVP_PKEY_CTX_ctrl.pod
  doc/man3/EVP_PKEY_new.pod
  doc/man3/EVP_PKEY_set1_RSA.pod
  include/crypto/asn1.h
  include/crypto/evp.h
  include/crypto/zuc.h
  include/openssl/cryptoerr.h
  include/openssl/evp.h
  include/openssl/evperr.h
  test/evp_test.c
  test/recipes/30-test_evp_data/evpmac.txt
  test/zuc_internal_test.c
  util/libcrypto.num
Labels: master, wait for 2nd review

#110 include && rpm : update version number to 8.3.0-dev
  include/openssl/opensslv.h
  rpm/babassl.spec
Labels: master, ready to merge

#116 Fix NTLS cert verify bug, cherry-pick master
  apps/apps.c
  apps/s_server.c
  crypto/x509/x_pubkey.c
  ssl/ssl_rsa.c
  ssl/statem_ntls/statem_clnt.c
  test/certs/CA.cert.pem
  test/certs/CA.cert.srl
  test/certs/CA.key.pem
  test/certs/CA.pem
  test/certs/CE.cert.pem
  test/certs/CE.key.pem
  test/certs/CE.pem
  test/certs/CS.cert.pem
  test/certs/CS.key.pem
  test/certs/CS.pem
  test/certs/SE.cert.pem
  test/certs/SE.key.pem
  test/certs/SE.pem
  test/certs/SS.cert.pem
  test/certs/SS.key.pem
  test/certs/SS.pem
  test/recipes/80-test_sign_sm2.t
  test/recipes/80-test_sign_sm2_data/ca.cnf
  test/recipes/80-test_sign_sm2_data/subca.cnf
  test/recipes/88-test_ssl_ntls_api.t
  test/ssl-tests/31-ntls.conf
  test/ssl-tests/31-ntls.conf.in
  test/ssl_test_ctx.c
  util/perl/OpenSSL/Test.pm
Labels: branch-8.2, wait for 2nd review

#119 add ntls alpn test cases
  ssl/t1_enc.c
  test/recipes/80-test_ssl_new.t
  test/ssl-tests/41-ntls-alpn.conf
  test/ssl-tests/41-ntls-alpn.conf.in
  test/ssl_test.c
Labels: master, branch-8.2, ready to merge

#122 Fix sm2 KDF, server should be initiator, not client
  crypto/sm2/sm2_kep.c
Labels: bug, master, ready to merge

#118 Support NTLS client authentication
  crypto/err/openssl.txt
  include/openssl/sslerr.h
  ssl/ssl_err.c
  ssl/statem_ntls/ssl_local_ntls.h
  ssl/statem_ntls/statem_clnt.c
  ssl/statem_ntls/statem_lib.c
  ssl/statem_ntls/statem_local_ntls.h
  ssl/statem_ntls/statem_ntls.c
  ssl/statem_ntls/statem_ntls_clnt.c
  ssl/statem_ntls/statem_ntls_srvr.c
  ssl/statem_ntls/statem_srvr.c
  test/recipes/80-test_sign_sm2.t
  test/recipes/80-test_ssl_new.t
  test/ssl-tests/40-ntls_client_auth.conf
  test/ssl-tests/40-ntls_client_auth.conf.in
Labels: enhancement, master
