Repository Tongsuo-Project/Tongsuo, pull requests merged in 2022-03, with the labels that each got.

#194 Fix egd and devrandom source configs
  crypto/rand/rand_unix.c
Labels: bug, master, branch-8.3

#201 Fix compilation issues on darwin64 arm64
  Configurations/00-base-templates.conf
  crypto/modes/build.info
  crypto/perlasm/arm-xlate.pl
Labels: bug, master, branch-8.3

#202 Delete NTLS unused code, supported_versions and extended_master_secret
  ssl/statem_ntls/statem_lib.c
  ssl/statem_ntls/statem_srvr.c
Labels: bug, master, branch-8.3

#210 Try to remove useless Camellia
  .github/workflows/ci.yml
  Configurations/00-base-templates.conf
  Configurations/README
  Configure
  INSTALL
  apps/openssl.c
  apps/progs.pl
  apps/speed.c
  config
  crypto/camellia/asm/cmll-x86.pl
  crypto/camellia/asm/cmll-x86_64.pl
  crypto/camellia/asm/cmllt4-sparcv9.pl
  crypto/camellia/build.info
  crypto/camellia/camellia.c
  crypto/camellia/cmll_cbc.c
  crypto/camellia/cmll_cfb.c
  crypto/camellia/cmll_ctr.c
  crypto/camellia/cmll_ecb.c
  crypto/camellia/cmll_local.h
  crypto/camellia/cmll_misc.c
  crypto/camellia/cmll_ofb.c
  crypto/engine/eng_devcrypto.c
  crypto/err/openssl.txt
  crypto/evp/build.info
  crypto/evp/c_allc.c
  crypto/evp/e_camellia.c
  crypto/evp/evp_err.c
  crypto/objects/obj_dat.h
  crypto/objects/obj_mac.num
  crypto/objects/objects.txt
  crypto/perlasm/sparcv9_modes.pl
  doc/man1/ciphers.pod
  doc/man1/dsa.pod
  doc/man1/enc.pod
  doc/man1/gendsa.pod
  doc/man1/genrsa.pod
  doc/man1/openssl.pod
  doc/man1/pkcs12.pod
  doc/man1/rsa.pod
  doc/man3/EVP_EncryptInit.pod
  doc/man3/EVP_camellia.pod
  fuzz/oids.txt
  include/openssl/camellia.h
  include/openssl/evp.h
  include/openssl/evperr.h
  include/openssl/obj_mac.h
  include/openssl/ssl.h
  include/openssl/tls1.h
  ssl/s3_lib.c
  ssl/ssl_ciph.c
  ssl/ssl_init.c
  ssl/ssl_local.h
  ssl/t1_trce.c
  test/ciphername_test.c
  test/evp_kdf_test.c
  test/recipes/30-test_evp_data/evpciph.txt
  util/find-doc-nits
  util/indent.pro
  util/libcrypto.num
Labels: master, ready to merge

#208 Update CHANGES.BabaSSL
  CHANGES.BabaSSL
Labels: master, ready to merge

#209 Update CHANGES.BabaSSL
  CHANGES.BabaSSL
Labels: ready to merge, branch-8.3

#213 Fix SM2 signature generation process issue
  crypto/sm2/sm2_sign.c
Labels: bug, master, branch-8.3

#218 Remove SEED cipher
  CHANGES
  CHANGES.en
  apps/openssl.c
  apps/progs.pl
  apps/speed.c
  crypto/evp/build.info
  crypto/evp/c_allc.c
  crypto/evp/e_seed.c
  crypto/objects/obj_dat.h
  crypto/objects/obj_mac.num
  crypto/objects/objects.txt
  crypto/seed/build.info
  crypto/seed/seed.c
  crypto/seed/seed_cbc.c
  crypto/seed/seed_cfb.c
  crypto/seed/seed_ecb.c
  crypto/seed/seed_local.h
  crypto/seed/seed_ofb.c
  doc/man1/ciphers.pod
  doc/man1/enc.pod
  doc/man1/openssl.pod
  doc/man3/EVP_seed_cbc.pod
  fuzz/oids.txt
  include/openssl/evp.h
  include/openssl/obj_mac.h
  include/openssl/seed.h
  include/openssl/ssl.h
  include/openssl/tls1.h
  ssl/s3_lib.c
  ssl/ssl_ciph.c
  ssl/ssl_init.c
  ssl/ssl_local.h
  ssl/t1_trce.c
  test/ciphername_test.c
  test/recipes/30-test_evp_data/evpciph.txt
  util/indent.pro
  util/libcrypto.num
Labels: master

#219 Synchronize bug fixes from master to 8.3-stable
  CHANGES.BabaSSL
  crypto/sm2/sm2_sign.c
Labels: branch-8.3
