Repository Tongsuo-Project/Tongsuo, pull requests merged in 2022-02, with the labels that each got.

#159 Fix a carry overflow bug in bn_sqr_comba4/8 for mips 32-bit targets
  crypto/bn/asm/mips.pl
  test/bntest.c
Labels: bug, master, branch-8.2

#162 Use SM2 and SM3 algorithms in TLS 1.3 as required in RFC 8998
  CHANGES.BabaSSL
  apps/speed.c
  crypto/err/openssl.txt
  crypto/evp/evp_err.c
  include/openssl/evperr.h
  include/openssl/kdferr.h
  include/openssl/sslerr.h
  include/openssl/tls1.h
  ssl/s3_lib.c
  ssl/ssl_err.c
  ssl/ssl_local.h
  ssl/statem/statem_clnt.c
  ssl/statem/statem_local.h
  ssl/statem/statem_srvr.c
  ssl/statem_ntls/statem_local_ntls.h
  ssl/t1_lib.c
  test/certs/sm2-root-crt.pem
  test/certs/sm2-root-key.pem
  test/handshake_helper.c
  test/handshake_helper.h
  test/recipes/30-test_evp_data/evpciph.txt
  test/ssl-tests/30-tls13-sm.conf
  test/ssl-tests/30-tls13-sm.conf.in
  test/ssl_test.c
  test/ssl_test_ctx.c
  test/ssl_test_ctx.h
Labels: enhancement, master

#157 apps/speed: add SM3/4 algorithm benchmark
  apps/speed.c
Labels: enhancement, master

#179 SM3 acceleration with SM3 hardware instruction on aarch64
  Configurations/00-base-templates.conf
  Configure
  crypto/arm64cpuid.pl
  crypto/arm_arch.h
  crypto/armcap.c
  crypto/sm3/asm/sm3-armv8.pl
  crypto/sm3/build.info
  crypto/sm3/sm3_local.h
Labels: enhancement, master

#182 SM4 optimization for ARM by HW instruction
  Configurations/00-base-templates.conf
  Configure
  crypto/arm64cpuid.pl
  crypto/arm_arch.h
  crypto/armcap.c
  crypto/evp/e_sm4.c
  crypto/sm4/asm/sm4-armv8.pl
  crypto/sm4/build.info
  include/crypto/sm4_platform.h
Labels: enhancement, master

#183 Prepare for BabaSSL 8.3.0 release
  CHANGES.BabaSSL
  include/openssl/opensslv.h
Labels: master

#185 Move to next version (8.3.1)
  CHANGES.BabaSSL
  include/openssl/opensslv.h
Labels: branch-8.3

#186 Move to next version (8.4.0)
  CHANGES.BabaSSL
  include/openssl/opensslv.h
Labels: master

#188 Move to next version (8.3.1)
  CHANGES.BabaSSL
  include/openssl/opensslv.h
Labels: branch-8.3
