Repository Tongsuo-Project/Tongsuo, pull requests merged in 2023-05, with the labels that each got.

#390 x509: excessive resource use verifying policy constraints
  crypto/x509/pcy_local.h
  crypto/x509/pcy_node.c
  crypto/x509/pcy_tree.c
Labels: bug, master

#391 x509: excessive resource use verifying policy constraints
  crypto/x509v3/pcy_local.h
  crypto/x509v3/pcy_node.c
  crypto/x509v3/pcy_tree.c
  test/certs/sm2-root.crt
Labels: bug, branch-8.3

#392 Ensure that EXFLAG_INVALID_POLICY is checked even in leaf certs
  crypto/x509/x509_vfy.c
Labels: bug, master

#394 Fix CVE-2023-1255
  crypto/aes/asm/aesv8-armx.pl
Labels: bug, master

#393 Ensure that EXFLAG_INVALID_POLICY is checked even in leaf certs
  crypto/x509/x509_vfy.c
Labels: bug, branch-8.3

#399 Fix the judgment condition of variable i
  test/punycode_test.c
Labels: bug, master

#411 Compute HMAC_SM3 of TLS/TLCP CBC record with ssl3_cbc_digest_record
  apps/speed.c
  crypto/sm3/m_sm3.c
  crypto/sm3/sm3.c
  crypto/sm3/sm3_local.h
  include/crypto/sm3.h
  include/openssl/sm3.h
  ssl/s3_cbc.c
  test/build.info
  test/recipes/03-test_sm3.t
  test/sm3_test.c
  util/libcrypto.num
Labels: bug, branch-8.3

#414 sm2: allows to disable Za via "sm2-za:no" parameter
  apps/lib/app_x509.c
  apps/lib/apps.c
  apps/lib/build.info
  apps/verify.c
  crypto/asn1/a_verify.c
  crypto/x509/x509_vfy.c
  crypto/x509/x_all.c
  include/crypto/x509.h
  include/openssl/core_names.h
  include/openssl/x509.h.in
  include/openssl/x509_vfy.h.in
  providers/implementations/signature/sm2_sig.c
  test/algorithmid_test.c
  test/certs/sm2-ca-cert.pem
  test/certs/sm2-cert.pem
  test/certs/sm2-csr.pem
  test/certs/sm2-first-crt.pem
  test/certs/sm2-first-key.pem
  test/certs/sm2-noza-cert.pem
  test/certs/sm2-noza-csr.pem
  test/certs/sm2-noza-root-cert.pem
  test/certs/sm2-root-cert.pem
  test/certs/sm2-root.crt
  test/certs/sm2-root.key
  test/certs/sm2.key
  test/certs/sm2.pem
  test/certs/sm2_begin_ec.key
  test/recipes/06-test_algorithmid.t
  test/recipes/20-test_pkeyutl.t
  test/recipes/25-test_req.t
  test/recipes/25-test_verify.t
  test/recipes/25-test_x509.t
  test/recipes/66-test_ossl_store.t
  test/recipes/80-test_ca.t
  test/ssl-tests/30-tls13-sm.cnf
  test/ssl-tests/30-tls13-sm.cnf.in
  util/libcrypto.num
Labels: enhancement, master

#419 Restrict the size of OBJECT IDENTIFIERs that OBJ_obj2txt will translate
  CHANGES
  crypto/objects/obj_dat.c
  test/smime-certs/mksmime-certs.sh
  test/smime-certs/smdh.pem
  test/smime-certs/smdsa1.pem
  test/smime-certs/smdsa2.pem
  test/smime-certs/smdsa3.pem
  test/smime-certs/smec1.pem
  test/smime-certs/smec2.pem
  test/smime-certs/smroot.pem
  test/smime-certs/smrsa1.pem
  test/smime-certs/smrsa2.pem
  test/smime-certs/smrsa3.pem
Labels: bug, branch-8.3

#420 Restrict the size of OBJECT IDENTIFIERs that OBJ_obj2txt will translate
  CHANGES
  crypto/objects/obj_dat.c
Labels: bug, master
