Repository Tongsuo-Project/Tongsuo, pull requests merged in 2023-02, with the labels that each got.

#349 Add EVP_sm4_gcm() and EVP_sm4_ccm
  crypto/evp/c_allc.c
  crypto/evp/e_sm4.c
  include/openssl/evp.h
  test/evp_extra_test.c
  util/libcrypto.num
Labels: master

#348 add force-ntls config option
  apps/s_server.c
  include/openssl/ssl.h.in
  ssl/ssl_conf.c
  ssl/ssl_lib.c
  ssl/ssl_local.h
  ssl/statem/statem.c
  test/ssl-tests/31-ntls.cnf
  test/ssl-tests/31-ntls.cnf.in
  test/ssl_ntls_api_test.c
  util/libssl.num
Labels: enhancement, master, wait for 2nd review

#358 Fix CVE-2023-0215, a UAF resulting from a bug in BIO_new_NDEF
  crypto/asn1/bio_ndef.c
Labels: bug, master

#359 Fix CVE-2022-4450
  crypto/pem/pem_lib.c
  test/pemtest.c
Labels: bug, master

#361 Fix CVE-2023-0216
  crypto/pkcs7/pk7_lib.c
Labels: bug, master

#362 Fix CVE-2023-0217
  crypto/ffc/ffc_key_validate.c
  include/internal/ffc.h
  test/ffc_internal_test.c
Labels: bug, master

#363 Fix CVE-2023-0401
  crypto/pkcs7/pk7_doit.c
Labels: bug, master

#364 Fix CVE-2022-4203
  crypto/x509/v3_ncons.c
Labels: bug, master

#366 Fix CVE-2023-0286
  crypto/x509/v3_genn.c
  include/openssl/x509v3.h.in
  test/v3nametest.c
Labels: bug, master

#346 s_server supports TLCP SNI test
  CHANGES
  apps/s_server.c
  engines/e_ossltest.c
  test/certs/sm2/server_enc2.crt
  test/certs/sm2/server_enc2.key
  test/certs/sm2/server_sign2.crt
  test/certs/sm2/server_sign2.key
  test/recipes/70-test_ntlssni.t
  util/perl/TLSProxy/Record.pm
Labels: enhancement, master

#357 Fix CVE-2023-0215, a UAF resulting from a bug in BIO_new_NDEF
  crypto/asn1/bio_ndef.c
  crypto/asn1/charmap.h
  crypto/bn/bn_prime.h
  crypto/conf/conf_def.h
  crypto/objects/obj_dat.h
  crypto/objects/obj_xref.h
  include/openssl/obj_mac.h
Labels: bug, branch-8.3

#360 Fix CVE-2022-4450
  crypto/pem/pem_lib.c
  test/pemtest.c
Labels: bug, branch-8.3

#365 Fix CVE-2023-0286
  crypto/x509v3/v3_genn.c
  include/openssl/x509v3.h
  test/v3nametest.c
Labels: bug, branch-8.3

#367 Fix CVE-2022-4304
  crypto/bn/bn_blind.c
  crypto/bn/bn_local.h
  crypto/bn/build.info
  crypto/bn/rsa_sup_mul.c
  crypto/rsa/rsa_ossl.c
  include/crypto/bn.h
Labels: bug, master

#368 Fix CVE-2022-4304
  crypto/bn/bn_blind.c
  crypto/bn/bn_err.c
  crypto/bn/bn_local.h
  crypto/bn/build.info
  crypto/bn/rsa_sup_mul.c
  crypto/err/openssl.txt
  crypto/rsa/rsa_ossl.c
  include/crypto/bn.h
  include/openssl/bnerr.h
Labels: bug, branch-8.3

#355 SSL_connection_is_ntls改成使用预读方式判断是否为NTLS，而不是peek
  CHANGES
  ssl/ssl_lib.c
  ssl/ssl_local.h
  ssl/statem_ntls/ntls_statem_lib.c
Labels: bug, master
