Repository Tongsuo-Project/Tongsuo, pull requests merged in 2023-03, with the labels that each got.

#374 修复加载具有显式参数的SM2私钥失败问题
  providers/implementations/encode_decode/decode_der2key.c
  test/recipes/06-test_algorithmid.t
Labels: bug, master

#342 Support zkp algorithm bulletproofs
  .github/workflows/ci.yml
  .github/workflows/speed-test.yml
  CHANGES
  Configure
  apps/build.info
  apps/bulletproofs.c
  apps/speed.c
  crypto/build.info
  crypto/ec/ec_lib.c
  crypto/err/openssl.ec
  crypto/err/openssl.txt
  crypto/zkp/build.info
  crypto/zkp/bulletproofs/bp_err.c
  crypto/zkp/bulletproofs/bullet_proof.c
  crypto/zkp/bulletproofs/bullet_proof.h
  crypto/zkp/bulletproofs/bullet_proof_asn1.c
  crypto/zkp/bulletproofs/bullet_proof_encode.c
  crypto/zkp/bulletproofs/bullet_proof_prn.c
  crypto/zkp/bulletproofs/debug.c
  crypto/zkp/bulletproofs/debug.h
  crypto/zkp/bulletproofs/inner_product.c
  crypto/zkp/bulletproofs/inner_product.h
  crypto/zkp/bulletproofs/util.c
  crypto/zkp/bulletproofs/util.h
  include/crypto/zkpbperr.h
  include/openssl/bulletproofs.h
  include/openssl/ec.h
  include/openssl/err.h.in
  include/openssl/zkpbperr.h
  test/build.info
  test/bullet_proof_test.c
  test/ectest.c
  test/recipes/03-test_bullet_proof.t
  test/recipes/80-test_app_bulletproofs.t
  util/libcrypto.num
  util/mkerr.pl
Labels: master

#378 Fix AES OCB encrypt/decrypt for x86 AES-NI
  crypto/aes/asm/aesni-x86.pl
Labels: bug, master

#380 Delete useless c_rehash
  .gitignore
  Configurations/descrip.mms.tmpl
  Configurations/unix-Makefile.tmpl
  Configurations/windows-makefile.tmpl
  Configure
  VMS/openssl_utils.com.in
  apps/rehash.c
  doc/man1/rehash.pod
  doc/man1/tsget.pod
  doc/man1/verify.pod
  doc/man1/x509.pod
  doc/man3/SSL_CTX_load_verify_locations.pod
  rpm/babassl.spec
  rpm/shangmi/babassl.spec
  tools/build.info
  tools/c_rehash.in
Labels: bug, branch-8.3
